# Generated by Django 4.2.30 on 2026-08-19 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_organization_is_ai_agent_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyOlapReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата отчета')),
                ('hour', models.IntegerField(verbose_name='Час (0-23)')),
                ('product_id', models.UUIDField(verbose_name='UUID Блюда/Товара')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название Блюда')),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Количество продаж')),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Выручка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_olap_reports', to='core.organization')),
            ],
            options={
                'verbose_name': 'Почасовые продажи блюда',
                'verbose_name_plural': 'Почасовые продажи блюд',
                'unique_together': {('organization', 'date', 'hour', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='DailyOlapReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата отчета')),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Выручка')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Себестоимость')),
                ('discounts', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Скидки')),
                ('checks_count', models.IntegerField(default=0, verbose_name='Количество чеков')),
                ('guests_count', models.IntegerField(default=0, verbose_name='Количество гостей')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_olap_reports', to='core.organization')),
            ],
            options={
                'verbose_name': 'Дневной отчет OLAP',
                'verbose_name_plural': 'Дневные отчеты OLAP',
                'unique_together': {('organization', 'date')},
            },
        ),
    ]
