# Generated by Django 4.2.30 on 2026-08-19 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alertlog'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IikoOlapPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type_key', models.CharField(choices=[('daily_kpi', 'Дневные продажи для KPI (Системный)'), ('hourly_sales', 'Почасовые продажи блюд (Системный)'), ('custom', 'Пользовательский отчет')], default='custom', max_length=50, verbose_name='Тип отчета')),
                ('name', models.CharField(max_length=255, verbose_name='Название отчета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание отчета')),
                ('preset_id', models.UUIDField(verbose_name='UUID пресета в iiko RMS')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системный отчет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olap_presets', to='core.organization')),
            ],
            options={
                'verbose_name': 'OLAP пресет iiko',
                'verbose_name_plural': 'OLAP пресеты iiko',
            },
        ),
        migrations.AddConstraint(
            model_name='iikoolappreset',
            constraint=models.UniqueConstraint(condition=models.Q(('report_type_key', 'custom'), _negated=True), fields=('organization', 'report_type_key'), name='unique_system_preset_per_org'),
        ),
    ]
