# Generated by Django 4.2.30 on 2026-08-19 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_organization_is_ai_agent_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.UUIDField(blank=True, null=True, verbose_name='UUID Поставщика')),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Поставщика')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('APPROVED', 'Утвержден'), ('SENT', 'Отправлен в iiko'), ('FAILED', 'Ошибка отправки')], default='DRAFT', max_length=20, verbose_name='Статус заказа')),
                ('iiko_document_id', models.UUIDField(blank=True, null=True, verbose_name='UUID Документа в iiko')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.organization')),
            ],
            options={
                'verbose_name': 'Заказ поставщику',
                'verbose_name_plural': 'Заказы поставщикам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StopListHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField(verbose_name='UUID Блюда')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название Блюда')),
                ('started_at', models.DateTimeField(verbose_name='Начало нахождения в стопе')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Выход из стопа')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Длительность простоя (сек)')),
                ('lost_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Упущенная выручка')),
                ('lost_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Упущенная валовая прибыль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_lists', to='core.organization')),
            ],
            options={
                'verbose_name': 'История стоп-листов',
                'verbose_name_plural': 'История стоп-листов',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField(verbose_name='UUID Ингредиента')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название Ингредиента')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество закупки')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Закупочная цена (из истории)')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder')),
            ],
            options={
                'verbose_name': 'Позиция заказа поставщику',
                'verbose_name_plural': 'Позиции заказов поставщикам',
            },
        ),
        migrations.CreateModel(
            name='ProductPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField(verbose_name='UUID Ингредиента/Товара')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('supplier_id', models.UUIDField(blank=True, null=True, verbose_name='UUID Поставщика')),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Поставщика')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Закупочная цена за единицу')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество закупки')),
                ('date', models.DateField(verbose_name='Дата прихода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_histories', to='core.organization')),
            ],
            options={
                'verbose_name': 'История закупки товара',
                'verbose_name_plural': 'История закупок товаров',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductInventoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField(verbose_name='UUID Ингредиента')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название Ингредиента')),
                ('min_stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Минимальный остаток (Min)')),
                ('max_stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Максимальный остаток (Max)')),
                ('target_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Плановая/Идеальная цена закупа')),
                ('responsible_role', models.CharField(choices=[('chef', 'Шеф-повар / Кухня'), ('barman', 'Бар-менеджер / Бар'), ('purchaser', 'Закупщик'), ('owner', 'Управляющий / Владелец')], default='chef', max_length=20, verbose_name='Ответственная роль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_rules', to='core.organization')),
            ],
            options={
                'verbose_name': 'Правило Min-Max остатков',
                'verbose_name_plural': 'Правила Min-Max остатков',
                'unique_together': {('organization', 'product_id')},
            },
        ),
    ]
