# Generated by Django 4.2.30 on 2026-05-20 15:14

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ресторана/сети')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Уникальный Slug')),
                ('address', models.TextField(blank=True, verbose_name='Фактический адрес')),
                ('tg_bot_token', apps.core.fields.EncryptedCharField(max_length=255, unique=True, verbose_name='Токен Telegram-бота')),
                ('tg_bot_username', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Username Telegram-бота (без @)')),
                ('tma_name', models.CharField(blank=True, max_length=100, verbose_name='Короткое имя Mini App в BotFather')),
                ('iiko_api_base_url', models.URLField(default='https://api-ru.iiko.services/api/1', verbose_name='iiko API Base URL')),
                ('iiko_api_login', apps.core.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='iiko API Login (API-ключ)')),
                ('iiko_organization_id', models.UUIDField(blank=True, null=True, verbose_name='iiko Organization ID')),
                ('iiko_loyalty_program_id', models.UUIDField(blank=True, null=True, verbose_name='iiko Loyalty Program ID')),
                ('branding', models.JSONField(blank=True, default=dict, help_text="Пример: {'design_color': '#FF5733', 'greeting_text': 'Добро пожаловать в Бургерную!'}", verbose_name='Настройки брендинга (цвета, логотип, приветствие)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
