# Generated by Django 4.2.30 on 2026-05-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='iiko_integration_type',
            field=models.CharField(choices=[('iiko_transport', 'iiko Cloud API (Transport)'), ('iiko_card', 'iikoCard (Legacy)')], default='iiko_transport', max_length=20, verbose_name='Тип интеграции с iiko'),
        ),
    ]
