# Generated by Django 4.2.30 on 2026-05-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_iiko_integration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='tg_bot_username',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Username Telegram-бота (без @)'),
        ),
    ]
