# Generated by Django 4.2.30 on 2026-05-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_organization_tg_bot_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='google_issuer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Google Issuer ID'),
        ),
        migrations.AddField(
            model_name='organization',
            name='google_loyalty_class_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Loyalty Class ID'),
        ),
    ]
