# Generated by Django 4.2.30 on 2026-05-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_google_issuer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='iiko_api_login',
            field=models.CharField(blank=True, max_length=255, verbose_name='iiko API Login (API-ключ)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tg_bot_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Токен Telegram-бота'),
        ),
    ]
