# Generated by Django 4.2.30 on 2026-05-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_organization_iiko_api_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='iiko_webhook_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль вебхука iiko (subscriptionPassword)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_iiko_webhook_password_enabled',
            field=models.BooleanField(default=False, verbose_name='Включить проверку пароля для Webhook'),
        ),
    ]
