# Generated by Django 4.2.30 on 2026-05-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_iiko_webhook_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AddField(
            model_name='organization',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp'),
        ),
    ]
