# Generated by Django 4.2.30 on 2026-05-25 12:07

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organization_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='iiko_api_login',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='iiko API Login (API-ключ)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tg_bot_token',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Токен Telegram-бота'),
        ),
    ]
