# Generated by Django 4.2.30 on 2026-05-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_organization_iiko_api_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tma_direct_link',
            field=models.URLField(blank=True, null=True, verbose_name='Прямая ссылка на TMA'),
        ),
    ]
