# Generated by Django 4.2.30 on 2026-08-06 10:57

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='iiko_app_id',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='iiko App ID'),
        ),
        migrations.AddField(
            model_name='organization',
            name='iiko_client_secret',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='iiko Client Secret'),
        ),
    ]
