# Generated by Django 4.2.30 on 2026-08-19 05:01

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_organization_iiko_app_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_ai_agent_enabled',
            field=models.BooleanField(default=False, verbose_name='Включен AI-агент'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_analytics_enabled',
            field=models.BooleanField(default=False, verbose_name='Включена аналитика и закупки'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_loyalty_enabled',
            field=models.BooleanField(default=True, verbose_name='Включена система лояльности'),
        ),
        migrations.AddField(
            model_name='organization',
            name='llm_api_key',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='API ключ LLM'),
        ),
        migrations.AddField(
            model_name='organization',
            name='llm_model_name',
            field=models.CharField(blank=True, default='gpt-4o-mini', max_length=100, verbose_name='Название модели'),
        ),
        migrations.AddField(
            model_name='organization',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek')], default='openai', max_length=20, verbose_name='Провайдер LLM'),
        ),
        migrations.AddField(
            model_name='organization',
            name='llm_system_prompt',
            field=models.TextField(blank=True, default='Вы — полезный AI-финансовый аналитик и закупщик для ресторана. Помогайте управлять заказами, анализировать фудкост, цены и упущенную выручку.', null=True, verbose_name='Системный промпт для AI-агента'),
        ),
    ]
