# Generated by Django 4.2.30 on 2026-08-19 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_organization_is_ai_agent_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50, verbose_name='Тип оповещения')),
                ('entity_id', models.UUIDField(blank=True, null=True, verbose_name='ID сущности (например, товара)')),
                ('message', models.TextField(verbose_name='Текст оповещения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='core.organization')),
            ],
            options={
                'verbose_name': 'Лог оповещения',
                'verbose_name_plural': 'Логи оповещений',
                'ordering': ['-created_at'],
            },
        ),
    ]
