# Generated by Django 4.2.30 on 2026-08-19 13:26

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alertlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='iiko_server_login',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='iiko Server Login'),
        ),
        migrations.AddField(
            model_name='organization',
            name='iiko_server_password',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='iiko Server Password'),
        ),
        migrations.AddField(
            model_name='organization',
            name='iiko_server_url',
            field=models.URLField(blank=True, null=True, verbose_name='iiko Server URL'),
        ),
    ]
