# Generated by Django 4.2.30 on 2026-05-25 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_organization_instagram_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название рассылки')),
                ('message_ru', models.TextField(verbose_name='Сообщение (RU)')),
                ('message_kz', models.TextField(verbose_name='Сообщение (KZ)')),
                ('scheduled_at', models.DateTimeField(verbose_name='Время отправки')),
                ('audience_type', models.CharField(choices=[('all', 'Все клиенты'), ('active', 'Активные (за последние 60 дней)'), ('inactive', 'Неактивные (более 60 дней)')], default='all', max_length=20, verbose_name='Целевой сегмент')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('in_progress', 'В процессе'), ('done', 'Завершена'), ('error', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='Размер целевой аудитории')),
                ('sent_success', models.PositiveIntegerField(default=0, verbose_name='Успешно отправлено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок отправки')),
                ('unsubscribed_count', models.PositiveIntegerField(default=0, verbose_name='Заблокировавших бота')),
                ('last_processed_user_id', models.IntegerField(default=0, verbose_name='ID последнего обработанного пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_tasks', to='core.organization')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
