# Generated by Django 4.2.30 on 2026-05-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bot_subscribed',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Подписан на бота'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('kz', 'Қазақша')], default='ru', max_length=10, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
