# Generated by Django 4.2.30 on 2026-05-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='points_balance',
        ),
        migrations.AddField(
            model_name='customer',
            name='iiko_card_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='iiko Card UUID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='iiko_card_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер карты iiko'),
        ),
        migrations.AddField(
            model_name='customer',
            name='iiko_categories',
            field=models.JSONField(blank=True, default=list, verbose_name='Категории в iiko'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс баллов'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='iiko_customer_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='iiko Customer UUID'),
        ),
    ]
