# Generated by Django 4.2.30 on 2026-05-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_remove_customer_points_balance_customer_iiko_card_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='google_wallet_object_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Wallet Object ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='wallet_barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Штрих-код'),
        ),
    ]
