# Generated by Django 4.2.30 on 2026-05-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_customer_google_wallet_object_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IikoWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.UUIDField(blank=True, null=True, verbose_name='iiko Organization ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='Тип события')),
                ('payload', models.JSONField(verbose_name='Тело вебхука (JSON)')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает обработки'), ('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
            ],
            options={
                'verbose_name': 'Лог вебхука iiko',
                'verbose_name_plural': 'Логи вебхуков iiko',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
