# Generated by Django 4.2.30 on 2026-05-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_iikowebhooklog_alter_customer_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('kz', 'Қазақша')], default='ru', max_length=2, verbose_name='Язык'),
        ),
    ]
