# Generated by Django 4.2.30 on 2026-05-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organization_instagram_link_and_more'),
        ('loyalty', '0005_customer_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок программы лояльности (RU)')),
                ('title_kz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок программы лояльности (KZ)')),
                ('description', models.TextField(verbose_name='Описание программы лояльности (RU)')),
                ('description_kz', models.TextField(blank=True, null=True, verbose_name='Описание программы лояльности (KZ)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_programs', to='core.organization')),
            ],
            options={
                'verbose_name': 'Программа лояльности',
                'verbose_name_plural': 'Программы лояльности',
                'ordering': ['-created_at'],
            },
        ),
    ]
