# Generated by Django 4.2.30 on 2026-05-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0006_loyaltyprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_bot_subscribed',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Согласие на рассылку'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Подтвержден'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата визита')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='loyalty.customer')),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиты',
            },
        ),
    ]
