# Generated by Django 4.2.30 on 2026-05-25 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0007_customer_is_bot_subscribed_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.UUIDField(db_index=True, verbose_name='iiko Wallet UUID')),
                ('name', models.CharField(max_length=255, verbose_name='Название программы лояльности / кошелька')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс баллов')),
                ('wallet_type', models.IntegerField(default=1, verbose_name='Тип кошелька')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='loyalty.customer')),
            ],
            options={
                'verbose_name': 'Кошелек клиента',
                'verbose_name_plural': 'Кошельки клиентов',
                'unique_together': {('customer', 'wallet_id')},
            },
        ),
    ]
